const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const YAML = require('yaml');
const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const source = JSON.parse(read('data/magnificent-jump-source.json'));
const slugs = ['magnificent-jump-intro', 'magnificent-jump-random-clock', 'magnificent-jump-variance-gamma'];
const canonical = html => html.replace(/<span[^>]*data-layout-only[^>]*>.*?<\/span>/gs, '').replace(/<!--.*?-->/gs, '').replace(/<[^>]+>/g, '');
const found = slugs.flatMap(slug => [...read(slug+'.md').matchAll(/^<div class="vg-source-block" data-source-block="(\d+)">(.+)<\/div>$/gm)]);
assert.equal(found.length, 85);
found.forEach((match, i) => { assert.equal(Number(match[1]), i); assert.equal(canonical(match[2]), canonical(source.blocks[i])); });
const toc = YAML.parse(read('_toc.yml'));
assert.equal(toc.chapters.length, 3);
assert.deepEqual(toc.chapters.map(c => c.file), slugs);
const notebook = JSON.parse(read('notebooks/the-magnificent-jump.ipynb'));
const blocks = notebook.cells.filter(c => c.metadata.source_block !== undefined);
assert.equal(blocks.length, 85);
blocks.forEach((cell,i) => { assert.equal(cell.metadata.source_block, i); assert.equal(canonical([].concat(cell.source).join('')), canonical(source.blocks[i])); });
const code = notebook.cells.filter(c => c.cell_type === 'code');
assert.deepEqual(code.map(c => c.execution_count), [1,2,3,4]);
const outputs = code.flatMap(c => c.outputs);
assert.equal(outputs.filter(o => o.data?.['image/png']).length, 3);
assert.equal(outputs.filter(o => o.output_type === 'error').length, 0);
assert.equal(YAML.parse(read('_config.yml')).repository.url, 'https://github.com/nutdnuy/the-magnificent-jump');
console.log('PASS: 85 original blocks preserved across three chapters and notebook; three figures and four executed cells.');
